const Relationship = require('../models/Relationship');
const TimelineEvent = require('../models/TimelineEvent');
const relService = require('../services/relationship.service');
const {
  nextMonthlyAnniversary,
  nextYearlyAnniversary,
  daysTogether,
  milestoneForDay,
} = require('../utils/anniversary');

/**
 * Generate anniversary and day-milestone timeline events.
 *
 * `first_anniversary`, `anniversary` and `milestone` existed in the TimelineEvent
 * enum but were NEVER generated — no job created them. The timeline therefore
 * only ever contained "firsts".
 *
 * Runs once a day. Every write is idempotent (guarded by an existence check on
 * the same event type and date) so a re-run cannot duplicate events.
 */
module.exports = (scheduleLocked) => {
  scheduleLocked('anniversaries', '5 6 * * *', async () => {
    const cursor = Relationship.find({ status: 'active', startDate: { $ne: null } }).cursor();

    let created = 0;
    for await (const rel of cursor) {
      try {
        created += await processRelationship(rel);
      } catch (err) {
        console.error(`[Cron:anniversaries] ${rel._id} failed:`, err.message);
      }
    }
    if (created) console.log(`[Cron:anniversaries] Created ${created} event(s)`);
  }, 10 * 60 * 1000);
};

/** Create an event only if one of the same type does not already exist that day. */
const ensureEvent = async (relationshipId, eventType, title, description, eventDate) => {
  const dayStart = new Date(eventDate);
  dayStart.setUTCHours(0, 0, 0, 0);
  const dayEnd = new Date(dayStart.getTime() + 24 * 60 * 60 * 1000);

  const exists = await TimelineEvent.exists({
    relationshipId,
    eventType,
    eventDate: { $gte: dayStart, $lt: dayEnd },
  });
  if (exists) return false;

  await TimelineEvent.create({
    relationshipId,
    eventType,
    title,
    description,
    eventDate,
    isAutoGenerated: true,
  });
  return true;
};

const processRelationship = async (rel) => {
  const today = new Date();
  const days = daysTogether(rel.startDate, today);
  let created = 0;

  const yearly = nextYearlyAnniversary(rel.startDate, today);
  const monthly = nextMonthlyAnniversary(rel.startDate, today);

  // Yearly anniversary — today only.
  if (yearly.daysUntil === 0 && yearly.yearsTogether >= 1) {
    const isFirst = yearly.yearsTogether === 1;
    if (await ensureEvent(
      rel._id,
      isFirst ? 'first_anniversary' : 'anniversary',
      isFirst ? 'First Anniversary 🎉' : `${yearly.yearsTogether} Years Together 🎉`,
      `${yearly.yearsTogether} year${yearly.yearsTogether > 1 ? 's' : ''} of you two.`,
      today
    )) {
      created++;
      await notifyBoth(rel, {
        title: isFirst ? 'Happy first anniversary! 🎉' : `Happy ${yearly.yearsTogether}-year anniversary! 🎉`,
        body: `${days} days together and counting.`,
        type: 'anniversary',
      });
    }
  } else if (monthly.daysUntil === 0 && monthly.monthsTogether >= 1 && monthly.monthsTogether % 12 !== 0) {
    // Monthly anniversary — skip when it coincides with a yearly one.
    if (await ensureEvent(
      rel._id,
      'milestone',
      `${monthly.monthsTogether} Months 💞`,
      `${monthly.monthsTogether} months together.`,
      today
    )) {
      created++;
      // Monthly milestones are timeline-only — no push, to avoid notification fatigue.
    }
  }

  // Day-count milestones (100, 365, 500, 1000, …).
  const milestone = milestoneForDay(days);
  if (milestone) {
    if (await ensureEvent(
      rel._id,
      'milestone',
      `${milestone} Days Together 🌟`,
      `You've been together for ${milestone} days.`,
      today
    )) {
      created++;
      await notifyBoth(rel, {
        title: `${milestone} days together 🌟`,
        body: 'That deserves a celebration.',
        type: 'milestone',
      });
    }
  }

  return created;
};

const notifyBoth = async (rel, { title, body, type }) => {
  for (const userId of [rel.user1, rel.user2].filter(Boolean)) {
    await relService.notifyUser(userId, {
      title,
      body,
      data: { type, relationshipId: String(rel._id) },
      relationshipId: rel._id,
    }).catch(() => {});
  }
};
