const mongoose = require('mongoose');

const timelineEventSchema = new mongoose.Schema({
  relationshipId: { type: mongoose.Schema.Types.ObjectId, ref: 'Relationship', required: true },
  eventType: {
    type: String,
    enum: ['first_connection', 'first_chat', 'first_photo', 'first_diary', 'first_music',
      'first_anniversary', 'anniversary', 'milestone', 'custom'],
    required: true,
  },
  title: { type: String, required: true },
  description: { type: String, default: '' },
  mediaUrl: { type: String, default: '' },
  eventDate: { type: Date, required: true },
  isAutoGenerated: { type: Boolean, default: false },
  isDeleted: { type: Boolean, default: false },
}, { timestamps: true });

module.exports = mongoose.model('TimelineEvent', timelineEventSchema);
